### PR TITLE
Update Mahara 22.10.0 for TKL18

### PR DESCRIPTION
**Pull request by UncleDan**
Thanks to @OnGle for mods.

### CODE REVIEW

**Comment by OnGle** [comment]
G'day @UncleDan, looks like we've both done some work on mahara. Although I didn't notice the gh releases and went source install route, this is probably better. If you're planning on finishing this one I found version 22.10.0 seemed to work, otherwise let me know.

**Comment by UncleDan** [comment]
I will check if I can make of O can make the 22.10 work and let you know

Daniele Lolli
w. www.danielelolli.it
m. +39 329 54 69 512

Il lun 7 ago 2023, 00:26 Stefan Davis ***@***.***> ha scritto:

**Comment by OnGle** [comment]
Hmm seems like you've hit the same issues I did, here's my code https://github.com/OnGle/mahara/tree/mahara-update

I pretty much just installed all the dependencies, built the css then uninstalled them again. Although iirc it doesn't "just work" after that, there's more issues.

**Comment by UncleDan** [comment]
Fixed merging @OnGle mods to make css

**Comment by OnGle** [comment]
This looks good too me, but add yourself into the changelog like this :) 

```
turnkey-mahara-18 (1) turnkey; urgency=low

  * Install latest community version of Mahara: 22.10.0 (see https://mahara.org/interaction/forum/topic.php?id=9290&post36681).
  [Daniel Lolli]

  * Re-build on TurnKey Linux 18 (Debian 12 'bookworm')
  [Daniel Lolli]

  * Note: Please refer to turnkey-core's changelog for changes common to all
    appliances. Here we only describe changes specific to this appliance.

 -- Stefan Davis <stefan@turnkeylinux.org>  Tue, 8 Aug 2023 19:00:00 +0200
 ```

**Comment by UncleDan** [comment]
Done @OnGle :wink:

**Review by OnGle — APPROVED** [review]
Looks good to me, thank you!

**Comment by JedMeister** [comment]
Apologies to you @UncleDan & @OnGle but due to https://github.com/turnkeylinux/tracker/issues/1922 we're going to need to deprecate this one... :(

**Pull request closed without merging**
